version: '3'

services:
  # PHP Application Service
  php-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    depends_on:
      - postgres-db

  # PostgreSQL Database Service
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: note_taking_app
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
